[mongodb]
localhost

[redis]
redis.dpspk142034.fun

[mysql]
mysql.dpspk142034.fun

[rabbitmq]
rabbitmq.dpspk142034.fun

[catalogue]
catalogue.dpspk142034.fun

[cart]
cart.dpspk142034.fun

[user]
user.dpspk142034.fun

[shipping]
shipping.dpspk142034.fun

[payment]
payment.dpspk142034.fun

[frontend]
frontend.dpspk142034.fun

[local]
localhost

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

[local:vars]
NAME=from inventory
; COURSE=Ansible
; DURATION=10HRS
; TRAINER=Sivakumar